//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.DomainDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.FaseModules = new HashSet<FaseModules>();
            this.ModuleCompetentie = new HashSet<ModuleCompetentie>();
            this.StudieBelasting = new HashSet<StudieBelasting>();
            this.StudiePunten = new HashSet<StudiePunten>();
            this.Weekplanning = new HashSet<Weekplanning>();
            this.Leerlijn = new HashSet<Leerlijn>();
            this.Tag = new HashSet<Tag>();
        }
    
        public string CursusCode { get; set; }
        public System.DateTime Schooljaar { get; set; }
        public string Beschrijving { get; set; }
        public string Naam { get; set; }
        public string Leedoelen { get; set; }
        public string Beoordelingen { get; set; }
        public string Organisatie { get; set; }
        public string Werkvorm { get; set; }
        public string Leermiddelen { get; set; }
        public string Verantwoordelijkheid { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<FaseModules> FaseModules { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<ModuleCompetentie> ModuleCompetentie { get; set; }
        public virtual ICollection<StudieBelasting> StudieBelasting { get; set; }
        public virtual ICollection<StudiePunten> StudiePunten { get; set; }
        public virtual ICollection<Weekplanning> Weekplanning { get; set; }
        public virtual ICollection<Leerlijn> Leerlijn { get; set; }
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
