//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.DomainDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opleiding
    {
        public string Naam { get; set; }
        public System.DateTime Schooljaar { get; set; }
        public string Beschrijving { get; set; }
        public string FaseNaam { get; set; }
        public System.DateTime FaseSchooljaar { get; set; }
    
        public virtual Fase Fase { get; set; }
    }
}
