//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.DomainDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opleiding
    {
        public Opleiding()
        {
            this.Fase = new HashSet<Fase>();
        }
    
        public string Naam { get; set; }
        public string Schooljaar { get; set; }
        public string Beschrijving { get; set; }
    
        public virtual ICollection<Fase> Fase { get; set; }
        public virtual Schooljaar Schooljaar1 { get; set; }
    }
}
