//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleManager.DomainDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudiePunten
    {
        public string CursusCode { get; set; }
        public int Schooljaar { get; set; }
        public string ToetsCode { get; set; }
        public decimal EC { get; set; }
        public string Minimum { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
