//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace ModuleManager.UserDAL {
    public partial class SysteemRol {
        public SysteemRol() {
            this.User = new HashSet<User>();
        }

        public string Role { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}
