//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNet.Identity.EntityFramework;
namespace ModuleManager.UserDAL {
    public partial class User :IdentityUser{
        public string UserNaam { get; set; }
        public string Wachtwoord { get; set; }
        public string SysteemRol { get; set; }
        public string email { get; set; }
        public string naam { get; set; }

        public virtual SysteemRol SysteemRol1 { get; set; }
    }
}
